import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const iconsDir = path.join(__dirname, '../src/icons');
const outputFile = path.join(__dirname, '../src/utils/iconRegistry.generated.mjs');

// Read all SVG files
const files = fs.readdirSync(iconsDir).filter(file => file.endsWith('.svg'));

let registryContent = `// Auto-generated icon registry
// This file is generated by scripts/generateIconRegistry.mjs
// Do not edit manually

export const iconRegistry = {\n`;

files.forEach(file => {
  const iconName = file.replace('.svg', '');
  const svgContent = fs.readFileSync(path.join(iconsDir, file), 'utf-8');
  // Escape backticks and backslashes in SVG content
  const escapedContent = svgContent.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
  registryContent += `  '${iconName}': \`${escapedContent}\`,\n`;
});

registryContent += `};\n`;

fs.writeFileSync(outputFile, registryContent);
console.log(`Generated icon registry with ${files.length} icons at ${outputFile}`);
